# full—The CLI installed on Linux with npm on a full Node.js installation, plus OpenJDK 11 and additional utilities such as jq.
FROM salesforce/cli:latest-rc-full

# Install basic development tools
RUN apt update && apt install -y sudo

# Ensure default user has access to `sudo`
ARG USERNAME=sfdx
ARG USER_UID=1001
ARG USER_GID=1000

# Note: "heroku" takes up the id of 1000:1000
RUN useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# Set `DEVCONTAINER` environment variable to help with orientation
ENV DEVCONTAINER=true
